[project]
name = "pagerduty-auto-ack"
version = "1.0.0"
description = "Automatic acks for the PagerDuty incidents"
authors = [{ name = "dezeroku", email = "dezeroku@gmail.com" }]
urls.Repository = "https://github.com/dezeroku/pagerduty-auto-ack"
license = "MIT"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = []

[project.scripts]
pagerduty-auto-ack = "pagerduty_auto_ack.cli:main"
